spring.application.name=log-authentication-service
server.servlet.context-path=/authentication-service
server.port=9069

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#data source configuration for postGre
spring.datasource.url=jdbc:postgresql://localhost:5432/log_inventory
spring.datasource.username=postgres
spring.datasource.password=Lipu@9938
spring.datasource.driver-class-name=org.postgresql.Driver

#keycloak end points for authentication
docmanager.keycloak.server-uri = http://localhost:8080

docmanager.keycloak.token.endpoint = http://localhost:8080/realms/logmanager/protocol/openid-connect/token
log.keycloak.logout.endpoint=http://localhost:8080/realms/logmanager/protocol/openid-connect/logout
docmanager.keycloak.admin.username = priyabrat9980@gmail.com
docmanager.keycloak.admin.password = Lipu@9938
docmanager.keycloak.client.id = log-ingestion
docmanager.keycloak.realm = logmanager
docmanager.keycloak.client.secret = MsRI99uRfV78aCKoiVFPWRr36QXjioZ9

#validate incoming jwt
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/logmanager
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/logmanager/protocol/openid-connect/certs
