spring.application.name=log-authentication-service
server.servlet.context-path=/authentication-service
server.port=9069

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#data source configuration for postGre
spring.datasource.url=jdbc:postgresql://localhost:5432/log_inventory
spring.datasource.username=******
spring.datasource.password=******
spring.datasource.driver-class-name=org.postgresql.Driver

auth.public.uri.access.key=*******************

#keycloak end points for authentication
docmanager.keycloak.server-uri =******************************

docmanager.keycloak.token.endpoint = http://localhost:8080/realms/logmanager/protocol/openid-connect/token
log.keycloak.logout.endpoint=http://localhost:8080/realms/logmanager/protocol/openid-connect/logout
docmanager.keycloak.admin.username = *****************
docmanager.keycloak.admin.password = **********
docmanager.keycloak.client.id = log-ingestion
docmanager.keycloak.realm = logmanager
docmanager.keycloak.client.secret = *****************

#validate incoming jwt
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/logmanager
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/logmanager/protocol/openid-connect/certs
