spring.application.name=authentication
server.port=8989

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#data source configuration for postGre
spring.datasource.url = jdbc:postgresql://localhost:5432/DOCMANAGER
spring.datasource.username = postgres
spring.datasource.password = docm@nager#9938
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#keycloak end points for authentication
docmanager.keycloak.server-uri = http://localhost:8080
docmanager.keycloak.token.endpoint = http://localhost:8080/realms/docmanager/protocol/openid-connect/token
docmanager.keycloak.admin.username = user
docmanager.keycloak.admin.password = user
docmanager.keycloak.client.id = doc-manager
docmanager.keycloak.realm = docmanager
docmanager.keycloak.client.secret = lwcJUJJCeitXwxdL3El0W3AvMr1cC81z

#validate incoming jwt
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/docmanager
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/docmanager/protocol/openid-connect/certs
